#!/usr/bin/env sh

IZPACK=$HOME/Software/IzPack
GAVROG=$PWD/..

jar cmf "$GAVROG/SYSTRE.MF" Systre.jar -C "$GAVROG/bin" org -C "$GAVROG/bin" buoy
jar cf 3dt-Main.jar -C "$GAVROG/bin" org

"$IZPACK/bin/compile" install.xml

rm Systre.jar 3dt-Main.jar
